### ISSUE TITLE
Orders report ignores Advanced filters

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#574] opened 2018-10-18 17:37 UTC
Setting an advanced filter in the _Orders report_ doesn't produce any change in the data displayed in the report.

**To Reproduce**
- Go to `/wp-admin/admin.php?page=wc-admin#/analytics/orders?filter=advanced&product_includes=123` (you might need to change `123` for a product id that exists in your system).

Expected result:
- Report summary, chart and table should only display data related to the product `123`.

Actual result:
- Report summary, chart and table display all data.

**Comment by psealock** [comment] 2018-10-24 22:33
https://github.com/woocommerce/wc-admin/pull/591 brings the advanced filters queries to the data requests, however the backend isn't accepting them just yet.

**Comment by timmyc** [comment] 2018-10-31 01:33
@psealock so is there additional API work that is needed to make the filters being sent function as expected? Is it affecting all filters or just some on certain endpoints?

**Comment by psealock** [comment] 2018-10-31 01:56
There needs to be additional work to accept the following parameters to the Order endpoints, https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_orders_stats

```
status_is
status_is_not
product_includes
product_excludes
code_includes
code_excludes
customer
match
```

At the moment, there is no `/reports/orders` endpoint to supply the table data (currently serviced by `/orders`). However, it should be subjected to the above parameters as well, so we'll need that endpoint also.

>Is it affecting all filters or just some on certain endpoints?

All other filters function as they should with the exception of Variations filters, which I'll address separately.

**Comment by psealock** [comment] 2018-12-03 20:09
This is a duplicate of #749, which has more info and a PR associated with it. Closing in favour of that one.

**Closed by psealock** 2018-12-03 20:09 UTC
Labels: Analytics, [Status] Blocked, [Type] Bug
