### ISSUE TITLE
Selected date range and dates in charts and tabular data don't match

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1667] opened 2019-02-21 22:53 UTC
**Describe the bug**
Dates in the report do not match the dates selected in the date range picker

<img width="1596" alt="screen shot 2019-02-21 at 2 46 10 pm" src="https://user-images.githubusercontent.com/4500952/53207068-911fab00-35e7-11e9-81ad-aa2bb814be87.png">

**To reproduce**

Select a specific date range, note the date range in the chart / and tabular data does not match the selected date range

**Comment by timmyc** [comment] 2019-02-21 22:55
I _think_ this might be a duplicate of #1651

**Comment by LevinMedia** [comment] 2019-02-21 23:53
@timmyc  _Maybe_ I' not sure... however this also seems to be affecting weekly date ranges as well... 

<img width="1558" alt="screen shot 2019-02-21 at 3 50 47 pm" src="https://user-images.githubusercontent.com/4500952/53209823-91707400-35f0-11e9-9a80-7206f7e066aa.png">

Also note in the screen shot above, when it's by week with the comparison period as "Last year" the comparison period dates don't line up, they're shifted forward by a day.

**Comment by psealock** [comment] 2019-03-06 00:40
hmm... same with #1651, I can't reproduce this one. The issues do look very similar.

**Comment by LevinMedia** [comment] 2019-03-07 03:07
The plot thickens... 

The default view for our analytics is "Month to date" 

when my computer and site are on LA time (It's 6:58pm on March 6th) - I get the following results 

![screen shot 2019-03-06 at 6 45 36 pm](https://user-images.githubusercontent.com/4500952/53929201-d01b1b00-4041-11e9-8ef9-0ecc357b36e5.png)

notice it's picking up the last day of feb in the chart, and although you can't see it in the screen shot, the 28th of feb is also in the tabular data. 

When I switch my computer to Auckland Time (3:58pm March 7th) stranger things happen: 

![screen shot 2019-03-07 at 3 50 32 pm](https://user-images.githubusercontent.com/4500952/53929367-618a8d00-4042-11e9-88a9-6a645e264bc9.png)

Auckland is a day ahead of my current time zone, so it should run from March 1 - 7, however, it's added one extra day in the future. 

Lastly, the first two ticks on the X axis are bunched up... all of these ticks should be spread out evenly across the axis. @psealock noted it's probably a separate issue.

**Comment by jeffstieler** [comment] 2019-03-11 23:46
https://github.com/woocommerce/wc-admin/pull/1778 should fix this, can you test @LevinMedia ?

**Comment by jeffstieler** [comment] 2019-03-12 13:36
@LevinMedia is that 👍 confirmation that it's fixed? Can this be closed?

**Comment by LevinMedia** [comment] 2019-03-12 17:46
Yep, sorry left a message over on #1778 looks good, Can be closed. Thanks!

**Closed** 2019-03-12 18:17 UTC
Labels: Analytics, [Type] Bug
