### ISSUE TITLE
Charts: Error: <g> attribute transform: Trailing garbage, "translate(0,NaN)"

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#854] opened 2018-11-15 00:38 UTC
**Describe the bug**

Occurs when loading the wp-admin > Revenue > Analytics page. The following appears in the console:

```

  | (anonymous) | @ | attr.js:31
-- | -- | -- | --
  | wc.components../node_modules/d3-selection/src/selection/each.js.__webpack_exports__.default | @ | each.js:5
  | wc.components../node_modules/d3-selection/src/selection/attr.js.__webpack_exports__.default | @ | attr.js:53
  | axis | @ | axis.js:102
  | wc.components../node_modules/d3-selection/src/selection/call.js.__webpack_exports__.default | @ | call.js:4
  | drawAxis | @ | utils.js:438
  | drawChart | @ | charts.js:89
  | drawChart


```

**To Reproduce**

1. Go to the wp-admin > Revenue > Analytics page
2. See error (8x)

**Expected behavior**

No error

**Screenshots**

<img width="1433" alt="screen shot 2018-11-14 at 4 37 20 pm" src="https://user-images.githubusercontent.com/1595739/48521971-a4262080-e82b-11e8-8030-f4b237a3ddce.png">

**Versions**

WP 5 w/o Gutenberg plugin

**Comment by Aljullu** [comment] 2018-11-15 23:21
This error appears when we are trying to render the chart but there is no data (#582). What's weird here and I couldn't reproduce yet is that we are trying to render the chart before the data is loaded.

**Comment by timmyc** [comment] 2018-12-12 19:05
Closing in favor of #582 as we should not render the chart without data.

**Closed by timmyc** 2018-12-12 19:05 UTC
Labels: [Type] Bug
