### ISSUE TITLE
REST API: Add Compare/Segment Support

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#846] opened 2018-11-14 15:55 UTC
Originally posted by @psealock on p7bje6-1bY-p2

Products, product categories, product variations, taxes and coupons have the ability to be compared against one another. Here is the design for comparison of variations of a product.

![product-detail---viewport-1366-2x](https://user-images.githubusercontent.com/22080/48494364-98623c00-e7e2-11e8-9f07-a974263cfbe1.png)

Looking at the Products Report, we will need to segment by products, categories, and variations. Would it be possible to include a query parameter such as `compareby` or `segmentby`?

**Comment by justinshreve** [comment] 2019-01-21 21:00
Closing as a duplicate of https://github.com/woocommerce/wc-admin/issues/1035.

**Closed by justinshreve** 2019-01-21 21:00 UTC
Labels: REST API
