### ISSUE TITLE
Database Update Done notice keeps reappearing after dismissing

### ISSUE THREAD

**Issue by JakeQZ** [woocommerce/wc-admin#7561] opened 2021-08-25 18:08 UTC
### Describe the bug
See woocommerce/woocommerce-admin#7264 and various other reports of this bug linked from there.

### To Reproduce
1. Update WooCommerce to 5.6.0
2. Wait for the database update to complete.
3. Visit the WooCommerce settings page.
4. Click "Thanks" in the WooCommerce database update done notice.

### Actual behavior:
There is an "Uncaught (in promise) Error" seen in the browser console log.  The page reloads and the notice reappears.  The notice also appears after navigating to other WooCommerce admin pages.

### Screenshots
See below for browser console log transcript.

### Expected behavior
No error is seen in the browser console.  The notice is dismissed, and does not reappear upon navigating to a WooCommerce admin page.  Probably the page should not reload when the notice is dismissed.

### Desktop
* OS: Windows 10 Home 21H1 x64
* Browser: Firefox
* Version 91.0.2 (64-bit)

### Smartphone
N/A

### Additional context
See woocommerce/woocommerce-admin#7264.  The notice did eventually disappear on one site, but I've found exactly the same problem on another site.

I've tested with all other plugins disabled and the Storefront theme (latest version, and WordPress 5.8.0), and can still reproduce the problem.

#### Browser console log
<details>

```
XHR POST https://example.org/wp-json/wc-analytics/admin/notes/11/action/56447?_locale=user
Uncaught (in promise) Error: 
    Mr https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=2.5.1:2
    Redux 31
    A https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    L https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    f https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    Ne https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    onClick https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=2.5.1:1
    ki https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:176
    ji https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    mi https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    lf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    wi https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:187
    Kd https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    pc https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    Wf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:34
    <anonymous> https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    uf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
    Qd https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
    sc https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    unstable_runWithPriority https://example.org/wordpress/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
index.js:2:44458
    Redux 3
    some self-hosted:163
    Redux 3
    some self-hosted:163
    Redux 4
    some self-hosted:163
    Redux 3
    some self-hosted:163
    Redux 4
    some self-hosted:163
    Redux 4
    some self-hosted:163
    Redux 3
    some self-hosted:163
    Redux 7
    A https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    L https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    f https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    Ne https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2
    onClick https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=2.5.1:1
    ki https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:176
    ji https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    mi https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    lf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
    wi https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:187
    Kd https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    pc https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
    Wf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:34
    <anonymous> https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    uf https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
    Qd https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
    sc https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    bind_applyFunctionN self-hosted:1373
    sc self-hosted:1336
    unstable_runWithPriority https://example.org/wordpress/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
    Da https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
    <anonymous> https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
    Ei https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
    bind_applyFunctionN self-hosted:1373
    Ei self-hosted:1336
GET https://example.org/wordpress/wp-admin/admin.php?page=wc-settings&wc-hide-notice=update&_wc_notice_nonce=fbc5e605d1
[HTTP/2 200 OK 735ms]
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. admin.php
GET https://example.org/wordpress/wp-includes/js/hoverintent-js.min.js?ver=2.2.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/components/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-admin/load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=5.8
GET https://example.org/content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.70
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/underscore.min.js?ver=1.8.3
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/backbone.min.js?ver=1.4.0
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/app/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/assets/js/jquery-tiptip/jquery.tipTip.min.js?ver=5.6.0
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.16
[HTTP/2 200 OK 0ms]
JQMIGRATE: Migrate is installed, version 3.3.2 load-scripts.php:5:709
GET https://example.org/content/plugins/woocommerce/assets/js/admin/woocommerce_admin.min.js?ver=5.6.0
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/assets/js/selectWoo/selectWoo.full.min.js?ver=1.0.6
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/assets/js/admin/wc-enhanced-select.min.js?ver=5.6.0
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-admin/load-scripts.php?c=0&load[chunk_0]=hoverIntent,regenerator-runtime,wp-polyfill,wp-hooks&ver=5.8
GET https://example.org/wordpress/wp-includes/js/dist/i18n.min.js?ver=5f1269854226b4dd90450db411a12b79
GET https://example.org/wordpress/wp-admin/js/common.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/admin-bar.min.js?ver=5.8
GET https://example.org/wordpress/wp-admin/js/svg-painter.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/heartbeat.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/wp-auth-check.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/shortcode.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/wp-util.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/wp-backbone.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/mediaelement/mediaelement-migrate.min.js?ver=5.8
GET https://example.org/wordpress/wp-includes/js/media-models.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/plupload/wp-plupload.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/mediaelement/wp-mediaelement.min.js?ver=5.8
GET https://example.org/wordpress/wp-includes/js/api-request.min.js?ver=5.8
GET https://example.org/wordpress/wp-includes/js/dist/dom-ready.min.js?ver=71883072590656bf22c74c7b887df3dd
GET https://example.org/wordpress/wp-includes/js/dist/a11y.min.js?ver=0ac8327cc1c40dcfdf29716affd7ac63
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/clipboard.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/media-views.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/media-editor.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/media-audiovideo.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/mce-view.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/imgareaselect/jquery.imgareaselect.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-admin/js/image-edit.min.js?ver=5.8
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/ui/draggable.min.js?ver=1.12.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/ui/slider.min.js?ver=1.12.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/jquery.ui.touch-punch.js?ver=0.2.2
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-admin/js/iris.min.js?ver=1.0.7
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/ui/menu.min.js?ver=1.12.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/ui/autocomplete.min.js?ver=1.12.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/includes/gateways/paypal/assets/js/paypal-admin.min.js?ver=5.6.0
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.19
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/vendor/moment.min.js?ver=2.29.1
GET https://example.org/wordpress/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-settings.js?ver=eb9fff9e86cd8c11bfb8c225bea87ed4
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/number/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/deprecated.min.js?ver=932d8bb37da8bbb396a7a3f754345e08
GET https://example.org/wordpress/wp-includes/js/dist/escape-html.min.js?ver=dcba9e40e8782c7d5883426934834b3e
GET https://example.org/wordpress/wp-includes/js/dist/html-entities.min.js?ver=26307b6ad1e445fc1a4643f634cb29c6
GET https://example.org/wordpress/wp-includes/js/dist/element.min.js?ver=581bce50da6025b17bd0d62a88f525a0
GET https://example.org/wordpress/wp-includes/js/dist/dom.min.js?ver=22e1cba3e717e77490ac4ae45f8ef8ee
GET https://example.org/wordpress/wp-includes/js/dist/is-shallow-equal.min.js?ver=9b8d91804cfb3ef5b14e6ef816664072
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/currency/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/date/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/keycodes.min.js?ver=042c4b19e6cbf332d429dea8aa3bf671
GET https://example.org/wordpress/wp-includes/js/dist/priority-queue.min.js?ver=b2e76fb9887a285b5eff38763f2ac2fc
GET https://example.org/wordpress/wp-includes/js/dist/compose.min.js?ver=6284a4846a73f9c3e3ff2d7bd0b47be7
GET https://example.org/wordpress/wp-includes/js/dist/date.min.js?ver=061439ac4325ef057b8f9c142c82a823
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/rich-text.min.js?ver=a4eb1e306ca234461cdecbca651dd8d9
GET https://example.org/wordpress/wp-includes/js/dist/primitives.min.js?ver=fedf57cf6da174d1eca2875b8b730af3
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/warning.min.js?ver=3e70e9d62208deeee510b84df4dec7f1
GET https://example.org/wordpress/wp-includes/js/dist/components.min.js?ver=72eccad5b704ebf3e45a24b4da1773fe
GET https://example.org/wordpress/wp-includes/js/dist/url.min.js?ver=41088521039aa510728086754722537c
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/navigation/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/api-fetch.min.js?ver=134e23b5f88ba06a093f9f92520a98df
GET https://example.org/wordpress/wp-includes/js/dist/autop.min.js?ver=0e55c6c10f6d8a4bd90b2ea903436301
GET https://example.org/wordpress/wp-includes/js/dist/blob.min.js?ver=4eca38a62df5f0145a5f1a78858581e7
GET https://example.org/wordpress/wp-includes/js/dist/block-serialization-default-parser.min.js?ver=2fc6dec19af6d4c5e5fec8f6fdc1a10b
GET https://example.org/wordpress/wp-includes/js/dist/blocks.min.js?ver=e2b6602c7ebbe8ce93832ce35d81be1c
GET https://example.org/wordpress/wp-includes/js/dist/shortcode.min.js?ver=5341d74d6385839c835c81ef7c751c59
GET https://example.org/wordpress/wp-includes/js/dist/data-controls.min.js?ver=cb4174d77c57f56732dc41d3bf3b2781
GET https://example.org/wordpress/wp-includes/js/dist/core-data.min.js?ver=594addbcbe24f4aeb531dcf64543c5b7
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/viewport.min.js?ver=79a37e9babb3e1cde045545771deed5e
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/csv-export/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/experimental/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/customer-effort-score/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/explat/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/notices.min.js?ver=302487dc7e2cc8ab91ae19a57631973c
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/dist/plugins.min.js?ver=c91bcc20b943e1d4ef09ca698c9a7c63
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/notices/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/tracks/index.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/wordpress/wp-includes/js/jquery/ui/datepicker.min.js?ver=1.12.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/assets/js/admin/settings.min.js?ver=5.6.0
[HTTP/2 200 OK 0ms]
`woocommerce_shared_settings` filter in Blocks is deprecated. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/block-assets.md admin.php:2590:9
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/3.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
GET https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=2.5.1
[HTTP/2 200 OK 0ms]
XHR GET https://example.org/wp-json/wc-analytics/admin/notes?page=1&per_page=25&status=unactioned&type[0]=info&type[1]=marketing&type[2]=survey&type[3]=warning&orderby=date&order=desc&_locale=user
[HTTP/2 200 OK 398ms]
XHR GET https://example.org/wp-json/wc-admin/options?options=woocommerce_ces_tracks_queue&_locale=user
[HTTP/2 200 OK 422ms]
XHR GET https://example.org/wp-json/wc-analytics/admin/notes?page=1&per_page=25&type=error,update&status=unactioned&_locale=user
[HTTP/2 200 OK 494ms]
GET https://example.org/favicon.ico
[HTTP/2 302 Found 0ms]
GET https://example.org/wordpress/wp-includes/images/w-logo-blue-white-bg.png
XHR POST https://example.org/wordpress/wp-admin/admin-ajax.php
[HTTP/2 200 OK 830ms]
```
</details>

##### Uncaught error details with `SCRIPT_DEBUG`
<details>

```
XHR POST https://example.org/wp-json/wc-analytics/admin/notes/11/action/57224?_locale=user
Navigated to https://example.org/wordpress/wp-admin/admin.php?page=wc-settings&wc-hide-notice=update&_wc_notice_nonce=fbc5e605d1
Uncaught (in promise) Error: 
    Mr https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=1629288206:2
    Redux 6
        yieldValue
        any
        next
        next
        unhandledActionControl
        next
index.js:2:44458
    Redux 3
        yieldValue
        any
        next
    some self-hosted:163
    Redux 3
        next
        unhandledActionControl
        next
    some self-hosted:163
    Redux 4
        next
        yieldValue
        any
        next
    some self-hosted:163
    Redux 3
        next
        unhandledActionControl
        next
    some self-hosted:163
    Redux 4
        next
        yieldValue
        (Async: promise callback)
    rungenControls
        next
    some self-hosted:163
    Redux 4
        next
        yieldValue
        any
        next
    some self-hosted:163
    Redux 3
        next
        unhandledActionControl
        next
    some self-hosted:163
    Redux 7
        next
        yieldValue
        iterate
        runtime
        createRuntime
        createRuntime
        createMiddleware
    promiseMiddleware https://example.org/wordpress/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:1571
    createResolversCacheMiddleware https://example.org/wordpress/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:1615
    createBoundAction https://example.org/wordpress/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2215
    useDispatchWithMap https://example.org/wordpress/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:3531
    onClick https://example.org/content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=1629288206:1
    callCallback https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:182
    invokeGuardedCallbackDev https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:231
    invokeGuardedCallback https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:286
    invokeGuardedCallbackAndCatchFirstError https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:300
    executeDispatch https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:383
    executeDispatchesInOrder https://example.org/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:408
GET https://example.org/wordpress/wp-admin/admin.php?page=wc-settings&wc-hide-notice=update&_wc_notice_nonce=fbc5e605d1
[HTTP/2 200 OK 673ms]
```
</details>

**Comment by octaedro** [comment] 2021-08-26 15:33
Thank you @JakeQZ for reporting this issue. It looks like it was already reported [here](woocommerce/woocommerce#32241).
I'm going to close this issue and refer to it in a comment there because it's still happening.

**Closed as completed by octaedro** 2021-08-26 15:33 UTC

**Comment by sparky672** [comment] 2021-09-16 21:26
Same here... actually have had this issue for a very long time, perhaps a year or more. Up to 5.8.1 and surprised to see it's still a lingering problem. Such a simple thing that needs to be bullet-proofed.

I shouldn't have to make manual edits to the database to hide this nag every time. One of the plugin developers over on the WordPress forum stated that if you don't click the button within 24 hours, then the nag persists forever. Seriously? He knows the cause and you can't fix this?

Not a big confidence booster when these simple things go on month after month until more than a year has passed... FWIW, I am a paying customer of WC products.

And there are so many open and closed bug reports on this issue, I don't even know where I am supposed to post.
